### ISSUE TITLE
Add macOS CI workflow

### ISSUE THREAD

**Issue by bhumitattarde** [zerodha/cppkiteconnect#36]
The boilerplate is ready, just need to add install commands like [this](https://github.com/zerodha/cppkiteconnect/blob/c9866982ba32dda609e61b85c930b4a0371d33a8/.github/workflows/cppkiteconnect-test.yml#L36). I took a crack at this (#35), but couldn't get it right because of not having access to a mac machine.

**Comment by rhnvrm** [comment]
@ajinasokan if free, possible to take look at this?

**Comment by ajinasokan** [comment]
Yes, let me see
