### ISSUE TITLE
Remove stray line breaks in source code

### ISSUE THREAD

**Issue by bhumitattarde** [zerodha/cppkiteconnect#4]

**Comment by 85ayush** [comment]
I would really love to work on this issue, I am a beginner to open source contribution, can you please guide me, I will give my 100%.

**Comment by bhumitattarde** [comment]
Hey @85ayush, 
Thank you for your interest. Unfortunately, most of the work is already done. You can, however, be on a lookout for issues in this repository. I anticipate more issues being reported as people start using the library.
