### ISSUE TITLE
Multiple definition issue in utils.hpp & config.hpp

### ISSUE THREAD

**Issue by navkamalrakra** [zerodha/cppkiteconnect#40]
Hi,

While developing using these API's , issue of multiple definitions is faced for isValid & _split function in the abovementioned files. 

This needs to be resolved either by separating their definition from declaration or specifying them as inline.

[bool isValid(int/double num) -> config.hpp](https://github.com/zerodha/cppkiteconnect/blob/1a7a0b8aaca1a2d7f29d5427dd4a384178bee607/include/kitepp/config.hpp#L80)
[std::vector<string> _split(const std::string& text, char sep) -> utils.hpp](https://github.com/zerodha/cppkiteconnect/blob/1a7a0b8aaca1a2d7f29d5427dd4a384178bee607/include/kitepp/utils.hpp#L34)

**Comment by bhumitattarde** [comment]
I can't reproduce this. How are you including the library? Are you on Windows? Share a minimal reproducible example, maybe?

`kitepp.hpp` is the only header that should be included. See [this example](https://github.com/zerodha/cppkiteconnect#rest-api) and [this project](https://github.com/bhumitattarde/kiteppex/blob/main/main.cpp) (it's very outdated but you get the idea).

**Comment by navkamalrakra** [comment]
I had this issue when I included kitepp.hpp in 2 different header files. Apologies for not sharing the system details :
I am ubuntu EC2 AWS instance. The issue resolved when I made the functions inline. I can share more reproducible details offline as I might have to share my code. 

I am aware of the examples and my code is working fine with this little change and I am able to generate session using these APIs.

**Comment by bhumitattarde** [comment]
Got it. I'll try to look into this.

**Comment by kushsharma2910** [comment]
Any updated on the same ?

**Comment by bhumitattarde** [comment]
@navkamalrakra @kushsharma2910 I'll fix this right away if you folks can provide a minimal reproducible example. 

I just set up a project that includes `kitepp.hpp` header in two different header files -- https://github.com/bhumitattarde/tmp-cppkiteconnect-bug-check, and I was able to run the built binary successfully.

**Comment by kushsharma2910** [comment]
Hi @bhumitattarde checkout this repo https://github.com/kushsharma2910/tmp-cppkiteconnect-bug-check, if you remove the inline keyword from the isValid and _split functions and try to make, it will show issues at the time of linking.

**Comment by bhumitattarde** [comment]
Thank you for providing an example. Just realized that it is an ODR violation. #43 should fix this.

**Comment by kushsharma2910** [comment]
It seems that only config.hpp has been changed. I think utils.hpp also needs to be updated in the same way. Thanks for the quick response.
