### ISSUE TITLE
Failed to send http/https request (enum code: 10)

### ISSUE THREAD

**Issue by anmolsinghal** [zerodha/cppkiteconnect#41]
**Describe the bug**
I am getting the error code in title when trying to run the example1 given in the directory. I am trying to run the code on AWS lightsail machine. Somehow I dont face this issue when running on my local ubuntu box. 

**Unit test output**
Output of ```make && make test ARGS='-V'```
Running tests...
Test project /home/ubuntu/cppkiteconnect
    Start 1: rapidjson-test
1/3 Test #1: rapidjson-test ...................   Passed    0.00 sec
    Start 2: kite-test
2/3 Test #2: kite-test ........................***Failed    0.01 sec
    Start 3: kiteWS-test
3/3 Test #3: kiteWS-test ......................***Failed    0.01 sec

33% tests passed, 2 tests failed out of 3

Total Test time (real) =   0.02 sec

The following tests FAILED:
          2 - kite-test (Failed)
          3 - kiteWS-test (Failed)
Errors while running CTest
make: *** [Makefile:84: test] Error 8

**Machine (please complete the following information):**
 - OS: Ubuntu 20.04

**Dependency versions**
OpenSSL 1.1.1i  8 Dec 2020,

**Comment by bhumitattarde** [comment]
AFAIK, this issue shows up when wrong OpenSSL is linked. Refer to #13 and more specifically [this](https://github.com/zerodha/cppkiteconnect/issues/13#issuecomment-945081192) comment.

Putting what worked for the person who last reported this here:

```
This issue had something to do with the openssl version that was getting linked. I reinstalled openssl and:

For compilers to find openssl@3 I had to set:
export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
```

**Comment by anmolsinghal** [comment]
Hi,

Thanks for the prompt reply. I had seen the thread but couldnt find the flags that need to be set for my case. 
Following is the output for ```openssl version -a```


OpenSSL 1.1.1i  8 Dec 2020
built on: Wed Mar  2 06:10:13 2022 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
Seeding source: os-specific

Could you tell me what values should LDFLAGS and CPPFLAGS hold?

**Comment by bhumitattarde** [comment]
I'd first make sure that cmake can actually find your OpenSSL installation. Run `ccmake` in the build directory and look for set OpenSSL paths. If they aren't specified, it means cmake cannot find your installation. You can them set them manually like `-DVARNAME=/path/to/zyx` while doing `cmake ..` or can put OpenSSL where cmake can find it (`echo $PATH` will give you set path; make sure it contains the directory where OpenSSL is stored.

AFAIK, `LDFLAGS` is used to specify link options and `CPPFLAGS` to specify C++ flags. The user has simply pointed cmake to their installation using these, you can do the same (using `-L` [lib path] and `-I` [include directory path] flags). I suggest you read their respective docs.

**Comment by bhumitattarde** [comment]
Closing this for now, Feel free to reopen if you keep facing the same issue.
