### ISSUE TITLE
Issue in isValid() function

### ISSUE THREAD

**Issue by kushsharma2910** [zerodha/cppkiteconnect#42]
This happened when I was trying to send a limit order in live market where isValid() returned false for DEFAULTDOUBLE as defined in the project.

For reproducing the issue checkout https://github.com/kushsharma2910/tmp-cppkiteconnect-bug-check/tree/nullValsComp. 

It seems that use of comparison operator == returns false value. Instead using std::isnan() function of the cmath library gives the correct output. 

Could you please take a look? Maybe I am missing something here. 

I am using c++11 on ubuntu 20.

**Comment by bhumitattarde** [comment]
Hey. thank you for reporting this. I'll take a look and update here.

**Comment by bhumitattarde** [comment]
#44 should work as long as the compiler doesn't optimize the comparison. I realize this is fragile but right now, it seems to be the best way to move forward without dropping Widows support or doing a big change.

**Comment by kushsharma2910** [comment]
Just to understand, according to the usage, we want to return true if default value was passed. for eg.

`if (!isValid(price)) { bodyParams.emplace_back("price", std::to_string(price)); }`

but now, I think, the signs would flip. 
I am missing something?

**Comment by bhumitattarde** [comment]
You seem to be correct. I'll check this.

**Comment by bhumitattarde** [comment]
This will be fixed in [`v2`](https://github.com/zerodha/cppkiteconnect/tree/v2).

**Comment by bhumitattarde** [comment]
`isValid` is phased out in `v2`.
