### ISSUE TITLE
Exception while subscribing to NIFTY50 in full mode: accessing vector out of bounds

### ISSUE THREAD

**Issue by sanchitabrol** [zerodha/cppkiteconnect#50]
Below line is causing an exception, packet size is 32 but we're accessing beyond that. I believe this should be 28, 31.
https://github.com/zerodha/cppkiteconnect/blob/aeef7d11eb92d34eb24a522212c165fbe4b70b84/include/kitepp/kitews.hpp#L477

**Comment by bhumitattarde** [comment]
Thank you for reporting this. Can you please check once #51 is once merged?
