### ISSUE TITLE
quote/ltp?i=NSE:NIFTY+50 returns empty body 

### ISSUE THREAD

**Issue by navkamalrakra** [zerodha/cppkiteconnect#61]
The following code does not return the values for NSE indices but works as expected for non NSE indices. 
```
std::vector<std::string> tempSymbols {"BSE:SENSEX", "NSE:NIFTY 50", "NSE:INFY", "NSE:FINNIFTY"};
std::unordered_map<std::string, kiteconnect::ltpQuote> temp = kiteObj->getLtp(tempSymbols);
for(auto & key : temp)
{
	std::cout << key.first << "\t" << key.second.lastPrice << "\n";
}
```
Below is the screenshot of the output when this code is run 
![1](https://github.com/zerodha/cppkiteconnect/assets/4273425/b090f431-405e-4f68-9e78-67f2ce64f1ee)

The request generated is (my token is blacked out):
![1 5](https://github.com/zerodha/cppkiteconnect/assets/4273425/723d0b33-d0d0-42ad-b3da-e1d87dbe296b)

The response received shows only the NSE indices values missing :
![2](https://github.com/zerodha/cppkiteconnect/assets/4273425/94d867ee-18a2-4a72-9172-b6c6d647a735)

The REST API seems to work as expected (again token blacked out) :
![3](https://github.com/zerodha/cppkiteconnect/assets/4273425/e96320cd-00d3-43c2-b1ac-7b340a1c8d12)

**Comment by bhumitattarde** [comment]
Thanks for reporting. I will try to reproduce this. A bit occupied at the moment so expect some delay in response.

**Comment by navkamalrakra** [comment]
Thanks @bhumitattarde Please try to take this on priority as this is a blocker issue for my algo.

**Comment by bhumitattarde** [comment]
@navkamalrakra #63 should solve this. If it doesn't, please report back here.

For `NSE:FINNIFTY`, REST API doesn't return anything so nothing I can do. Try the Kite forum. 

```sh
curl "https://api.kite.trade/quote/ltp?i=NSE:FINNIFTY" \                                                                                                                                                                    
  -H "X-Kite-Version: 3" \
  -H "Authorization: token key:at"
```

```json
{"status":"success","data":{}}
```
