### ISSUE TITLE
getInstruments call is throwing libException

### ISSUE THREAD

**Issue by navkamalrakra** [zerodha/cppkiteconnect#62]
```
std::vector<kc::instrument> inst = kiteObj->getInstruments(kiteconnect::EXCHANGE_NFO);
	for (auto const& i : inst) {
		std::cout << "symbol: " << i.tradingsymbol
				<< " token: " << i.instrumentToken << '\n';
	};
```

throws libException as the response is csv but parse method in kitepp/utils.hpp gets json flag as true and csv content is tried to be parsed as json, thus throwing the exception.

Workaround : For now I am checking maually if content can be parsed as json and then resetting the json flag but this workaround is not stable and proper fix needs to be in place.

![image](https://github.com/zerodha/cppkiteconnect/assets/4273425/b79d5a53-3c37-417f-ac82-f860060eb6a8)

**Comment by bhumitattarde** [comment]
Thanks for reporting. #64 should fix this. If it doesn't, report back here.
