### ISSUE TITLE
macos ci failing

### ISSUE THREAD

**Issue by bhumitattarde** [zerodha/cppkiteconnect#68]
This command in macos ci is failing:

`brew extract --version=1.10.0 googletest homebrew/cask`

with:

`Error: Cannot extract formula to homebrew/cask!`

@rhnvrm Possible to get help of someone who has a mac and can update the command?

Entire command: 

```sh
brew extract --version=1.10.0 googletest homebrew/cask && brew install googletest@1.10.0 libuv
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
```

Workflow:

https://github.com/zerodha/cppkiteconnect/actions/runs/5996845034/job/16262099686?pr=67

**Comment by rhnvrm** [comment]
cc @ajinasokan
