### ISSUE TITLE
Price should not be declared as int

### ISSUE THREAD

**Issue by navkamalrakra** [zerodha/cppkiteconnect#70]
[Price is declared as int and it causes huge issues while calculating LIMIT orders](https://github.com/zerodha/cppkiteconnect/blob/6a0bd7fd077ff792678020e00557b8818647fc60/include/kitepp/responses/order.hpp#L67). This should be updated to double.

**Comment by bhumitattarde** [comment]
Thanks for reporting this. Linked PR should fix it.
